/*
 * \file config.h
 * This file is part of SmithDR.
 * Licence details can be found in the file COPYING.
 *
 * This is the compilation configuration file for SmithDR.
 * It was generated by cmake.
 * You might want to change some of the defaults if something goes wrong
 * during the compilation.
 */

#ifndef _CONFIG_H
#define _CONFIG_H

// obligatory flags
#define QT_NO_STL
#define QT_NO_KEYWORDS

#cmakedefine PACKAGE "${PACKAGE}"
#cmakedefine PACKAGE_VERSION "${PACKAGE_VERSION}"
#define PACKAGE_STRING "SmithDR ${PACKAGE_VERSION}"
#cmakedefine PACKAGE_BUGREPORT "${PACKAGE_BUGREPORT}"
#cmakedefine SMITHDR_DATE "${SMITHDR_DATE}"
#cmakedefine VERSION_INFO "${VERSION_INFO}"
#cmakedefine SMITHDR_DIR_VER "${SMITHDR_DIR_VER}"
#cmakedefine SMITHDR_USERDIR_VER "${SMITHDR_USERDIR_VER}"
#define SMITHDR_MAJOR_VERSION ${SMITHDR_MAJOR_VERSION}
#define SMITHDR_MINOR_VERSION ${SMITHDR_MINOR_VERSION}

#define PROGRAM_SUFFIX "${PROGRAM_SUFFIX}"
#define SMITHDR_ABS_INSTALLED_DATADIR "${SMITHDR_ABS_INSTALLED_DATADIR}"
#define SMITHDR_ABS_INSTALLED_LOCALEDIR "${SMITHDR_ABS_INSTALLED_LOCALEDIR}"
#define SMITHDR_ABS_TOP_SRCDIR "${TOP_SRC_DIR}"

#cmakedefine USE_POSIX_PACKAGING 1
#cmakedefine USE_WINDOWS_PACKAGING 1
#cmakedefine USE_MACOSX_PACKAGING 1
#cmakedefine PATH_MAX ${PATH_MAX}

#cmakedefine WORDS_BIGENDIAN 1

#cmakedefine SMITHDR_USE_TR1 1
#cmakedefine SMITHDR_USE_TR1_REGEX 1

#endif // config.h guard
